# Generated by Django 5.2 on 2025-04-06 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x1', models.BigIntegerField()),
                ('y1', models.BigIntegerField()),
                ('x2', models.BigIntegerField()),
                ('y2', models.BigIntegerField()),
            ],
        ),
    ]
