# Generated by Django 5.2 on 2025-04-06 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cub', '0003_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='description',
            field=models.CharField(default='This is position bacterium', max_length=500),
        ),
        migrations.AlterField(
            model_name='position',
            name='name',
            field=models.CharField(default='position', max_length=100),
        ),
        migrations.AlterField(
            model_name='position',
            name='r',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='position',
            name='x',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='position',
            name='y',
            field=models.FloatField(default=0),
        ),
    ]
