# Generated by Django 5.2 on 2025-04-13 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cub', '0005_dots_vision'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top', models.BigIntegerField(default=0)),
                ('left', models.BigIntegerField(default=0)),
                ('div_id', models.CharField(max_length=100, unique=True)),
                ('height', models.BigIntegerField(default=10)),
                ('width', models.BigIntegerField(default=10)),
            ],
        ),
        migrations.AddField(
            model_name='edge',
            name='pref_parent_id',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
