from django.db import models
from django.utils import timezone

class Food_db(models.Model):
    top = models.BigIntegerField(default=0)
    left = models.BigIntegerField(default=0)
    div_id = models.CharField(max_length=100,unique=True)
    height = models.BigIntegerField(default=10)
    width = models.BigIntegerField(default=10)
    def __str__(self):
        """Returns a string representation of a controler."""
        return self.div_id

class Edge(models.Model):
    x1 = models.BigIntegerField()
    y1 = models.BigIntegerField()
    x2 = models.BigIntegerField()
    y2 = models.BigIntegerField()
    pref_parent_id = models.CharField(max_length=1000)
    def __str__(self):
        """Returns a string representation of a edge."""
        return f"'{str(self.x1)}':'{str(self.y1)}', '{str(self.x2)}':'{str(self.y2)}'"

class Controler(models.Model):
    value = models.BigIntegerField()
    name = models.CharField(max_length=100)
    description = models.CharField(max_length=500)
    def __str__(self):
        """Returns a string representation of a controler."""
        return self.name

class Position(models.Model):
    x = models.FloatField(default=0)
    y = models.FloatField(default=0)
    r = models.FloatField(default=0)
    name = models.CharField(max_length=100, default="position")
    description = models.CharField(max_length=500, default="This is position bacterium")
    def __str__(self):
        """Returns a string representation of a position."""
        return f"'x':'{str(self.x)}', 'y':'{str(self.y)}', 'r':'{str(self.r)}'"
    
class Dots(models.Model):
    x1 = models.FloatField(default=456.4626)
    y1 = models.FloatField(default=416.9124)
    x2 = models.FloatField(default=485.1517)
    y2 = models.FloatField(default=408.1413)
    x3 = models.FloatField(default=490.9992)
    y3 = models.FloatField(default=427.2674)
    x4 = models.FloatField(default=462.31)
    y4 = models.FloatField(default=436.0385)
    r = models.FloatField(default=-17.0)
    name = models.CharField(max_length=100, default="dots")
    description = models.CharField(max_length=500, default="These are 4 dots on the vertices of the bacterium")
    def __str__(self):
        """Returns a string representation of a dots."""
        return self.name
    
class Vision(models.Model):
    s00 = models.FloatField(default=0)
    c00 = models.FloatField(default=0)
    s01 = models.FloatField(default=0)
    c01 = models.FloatField(default=0)
    s02 = models.FloatField(default=0)
    c02 = models.FloatField(default=0)
    s03 = models.FloatField(default=0)
    c03 = models.FloatField(default=0)
    s04 = models.FloatField(default=0)
    c04 = models.FloatField(default=0)
    s05 = models.FloatField(default=0)
    c05 = models.FloatField(default=0)
    s06 = models.FloatField(default=0)
    c06 = models.FloatField(default=0)
    s07 = models.FloatField(default=0)
    c07 = models.FloatField(default=0)
    s08 = models.FloatField(default=0)
    c08 = models.FloatField(default=0)
    s09 = models.FloatField(default=0)
    c09 = models.FloatField(default=0)
    s10 = models.FloatField(default=0)
    c10 = models.FloatField(default=0)
    s11 = models.FloatField(default=0)
    c11 = models.FloatField(default=0)
    s12 = models.FloatField(default=0)
    c12 = models.FloatField(default=0)
    s13 = models.FloatField(default=0)
    c13 = models.FloatField(default=0)
    s14 = models.FloatField(default=0)
    c14 = models.FloatField(default=0)
    s15 = models.FloatField(default=0)
    c15 = models.FloatField(default=0)
    s16 = models.FloatField(default=0)
    c16 = models.FloatField(default=0)
    s17 = models.FloatField(default=0)
    c17 = models.FloatField(default=0)
    s18 = models.FloatField(default=0)
    c18 = models.FloatField(default=0)
    s19 = models.FloatField(default=0)
    c19 = models.FloatField(default=0)
    s20 = models.FloatField(default=0)
    c20 = models.FloatField(default=0)
    s21 = models.FloatField(default=0)
    c21 = models.FloatField(default=0)
    s22 = models.FloatField(default=0)
    c22 = models.FloatField(default=0)
    s23 = models.FloatField(default=0)
    c23 = models.FloatField(default=0)
    s24 = models.FloatField(default=0)
    c24 = models.FloatField(default=0)
    s25 = models.FloatField(default=0)
    c25 = models.FloatField(default=0)
    s26 = models.FloatField(default=0)
    c26 = models.FloatField(default=0)
    s27 = models.FloatField(default=0)
    c27 = models.FloatField(default=0)
    s28 = models.FloatField(default=0)
    c28 = models.FloatField(default=0)
    s29 = models.FloatField(default=0)
    c29 = models.FloatField(default=0)
    s30 = models.FloatField(default=0)
    c30 = models.FloatField(default=0)
    s31 = models.FloatField(default=0)
    c31 = models.FloatField(default=0)
    s32 = models.FloatField(default=0)
    c32 = models.FloatField(default=0)
    s33 = models.FloatField(default=0)
    c33 = models.FloatField(default=0)
    s34 = models.FloatField(default=0)
    c34 = models.FloatField(default=0)
    s35 = models.FloatField(default=0)
    c35 = models.FloatField(default=0)
    s36 = models.FloatField(default=0)
    c36 = models.FloatField(default=0)
    s37 = models.FloatField(default=0)
    c37 = models.FloatField(default=0)
    s38 = models.FloatField(default=0)
    c38 = models.FloatField(default=0)
    s39 = models.FloatField(default=0)
    c39 = models.FloatField(default=0)
    s40 = models.FloatField(default=0)
    c40 = models.FloatField(default=0)
    s41 = models.FloatField(default=0)
    c41 = models.FloatField(default=0)
    s42 = models.FloatField(default=0)
    c42 = models.FloatField(default=0)
    s43 = models.FloatField(default=0)
    c43 = models.FloatField(default=0)
    s44 = models.FloatField(default=0)
    c44 = models.FloatField(default=0)
    s45 = models.FloatField(default=0)
    c45 = models.FloatField(default=0)
    s46 = models.FloatField(default=0)
    c46 = models.FloatField(default=0)
    s47 = models.FloatField(default=0)
    c47 = models.FloatField(default=0)
    s48 = models.FloatField(default=0)
    c48 = models.FloatField(default=0)
    s49 = models.FloatField(default=0)
    c49 = models.FloatField(default=0)
    s50 = models.FloatField(default=0)
    c50 = models.FloatField(default=0)
    s51 = models.FloatField(default=0)
    c51 = models.FloatField(default=0)
    s52 = models.FloatField(default=0)
    c52 = models.FloatField(default=0)
    s53 = models.FloatField(default=0)
    c53 = models.FloatField(default=0)
    s54 = models.FloatField(default=0)
    c54 = models.FloatField(default=0)
    s55 = models.FloatField(default=0)
    c55 = models.FloatField(default=0)
    s56 = models.FloatField(default=0)
    c56 = models.FloatField(default=0)
    s57 = models.FloatField(default=0)
    c57 = models.FloatField(default=0)
    s58 = models.FloatField(default=0)
    c58 = models.FloatField(default=0)
    s59 = models.FloatField(default=0)
    c59 = models.FloatField(default=0)
    # name = models.CharField(max_length=100, default="vision")
    # description = models.CharField(max_length=500, default="What the bacteria sees")
    def __str__(self):
        """Returns a string representation of a vision."""
        return "vision - What the bacteria sees"
# vision - eyes
# dots - test